const Fighters = [
  {
    id: 1,
    fighter: "Yuki Ichidoji",
    card: "../assets/card-img/gramgrace-sieg.png",
    nation: "Keter Sanctuary",
    main: "Sword Saint Knight Dragon Emperor, Gramgrace Sieg",
    level: ["Hard", "Very Hard"],
  },
  {
    id: 2,
    fighter: "Rasen Ichidoji",
    card: `../assets/card-img/rorowa.png`,
    nation: "Stoicheia",
    main: "A Viridescent Flash, Rorowa",
    level: ["Easy", "Normal", "Hard", "Very Hard"],
  },
  {
    id: 3,
    fighter: "Gosetsu Katsushika",
    card: `../assets/card-img/flagburg.png`,
    nation: "Stoicheia",
    main: "Flagship Dragon, Flagburg Dragon",
    level: ["Easy", "Normal", "Hard", "Very Hard"],
  },
  {
    id: 4,
    fighter: "Kanji Meguro",
    card: `../assets/card-img/favrneel.png`,
    nation: "Dark States",
    main: "Purgatory Dragon Deity, Favrneel",
    level: ["Easy", "Normal", "Hard", "Very Hard"],
  },
  {
    id: 5,
    fighter: "Tatsuki Bunkyo",
    card: `../assets/card-img/kheios.png`,
    nation: "Dark States",
    main: "Soul Oratorio, Kheios",
    level: ["Easy", "Normal", "Hard", "Very Hard"],
  },
  {
    id: 6,
    fighter: "Masaru Kita",
    card: "../assets/card-img/baromagnes.png",
    nation: "Dark States",
    main: "Master of Gravity, Baromagnes",
    level: ["Easy", "Normal", "Hard", "Very Hard"],
  },
  {
    id: 7,
    fighter: "Danji Momoyama",
    card: "../assets/card-img/bruce.png",
    nation: "Dark States",
    main: 'Diabolos, "Viamance" Bruce',
    level: ["Hard", "Very Hard"],
  },
  {
    id: 8,
    fighter: "Suo Yobitsugi",
    card: "../assets/card-img/blangdmire.png",
    nation: "Dark States",
    main: "Fated One of Zero, Blangdmire",
    level: ["Hard", "Very Hard"],
  },
  {
    id: 9,
    fighter: "Michiru Hazama",
    card: "../assets/card-img/drajeweled.png",
    nation: "Dark States",
    main: "Demonic Jewel True Dragon, Drajeweled Ignis",
    level: ["Very Hard"],
  },
  {
    id: 10,
    fighter: "Haru Shinigawa",
    card: "../assets/card-img/thegrea.png",
    nation: "Keter Sanctuary",
    main: "Epee De Justice, Thegrea",
    level: ["Normal", "Hard", "Very Hard"],
  },
  {
    id: 11,
    fighter: "Kuro Minato",
    card: "../assets/card-img/hexaorb.png",
    nation: "Keter Sanctuary",
    main: `Hexaorb Sorceress, "Aquamarine"`,
    level: ["Easy", "Normal", "Hard", "Very Hard"],
  },
  {
    id: 12,
    fighter: "Kisato Kuga",
    card: "../assets/card-img/majestylordblaster.png",
    nation: "Keter Sanctuary",
    main: "Majesty Lord Blaster",
    level: ["Normal", "Hard", "Very Hard"],
  },
  {
    id: 13,
    fighter: "Gaku Nijo",
    card: "../assets/card-img/luard.png",
    nation: "Keter Sanctuary",
    main: "Dragheart, Luard",
    level: ["Normal", "Hard", "Very Hard"],
  },
  {
    id: 14,
    fighter: "Raika Koshiba",
    card: "../assets/card-img/youthberk.png",
    nation: "Keter Sanctuary",
    main: 'Youthberk "RevolForm: Full Blast"',
    level: ["Hard", "Very Hard"],
  },
  {
    id: 15,
    fighter: "Akina Myodo",
    card: "../assets/card-img/rezael.png",
    nation: "Keter Sanctuary",
    main: "Fated One of Miracles, Rezael",
    level: ["Hard", "Very Hard"],
  },
  {
    id: 16,
    fighter: "Hikari Myodo",
    card: "../assets/card-img/amorta.png",
    nation: "Keter Sanctuary",
    main: "Fated One of Time, Liael=Amorta",
    level: ["Very Hard"],
  },
  {
    id: 17,
    fighter: "Megumi Okura",
    card: "../assets/card-img/magnolia.png",
    nation: "Stoicheia",
    main: "Sylvan Horned Beast Emperor, Magnolia Elder",
    level: ["Very Hard"],
  },
  {
    id: 18,
    fighter: "Urara Haneyama",
    card: "../assets/card-img/lianorn.png",
    nation: "Stoicheia",
    main: "Marche Fleur, Lianorn Vivace",
    level: ["Hard", "Very Hard"],
  },
  {
    id: 19,
    fighter: "Masenori Iseki",
    card: "../assets/card-img/zorga.png",
    nation: "Stoicheia",
    main: "Fated One of Taboo, Zorga Nadir",
    level: ["Hard", "Very Hard"],
  },
  {
    id: 20,
    fighter: "Mika Shibuya",
    card: "../assets/card-img/kairi.png",
    nation: "Lyrical Monasterio",
    main: "AstesicexLive, Kairi",
    level: ["Easy", "Normal", "Hard", "Very Hard"],
  },
  {
    id: 21,
    fighter: "Kana Aoyama",
    card: "../assets/card-img/fortia.png",
    nation: "Lyrical Monasterio",
    main: "Full Moon Magic, Fortia",
    level: ["Normal", "Hard", "Very Hard"],
  },
  {
    id: 22,
    fighter: "Yui Itabashi",
    card: "../assets/card-img/loronerol.png",
    nation: "Lyrical Monasterio",
    main: "Heartfelt Song, Loronerol",
    level: ["Normal", "Hard", "Very Hard"],
  },
  {
    id: 23,
    fighter: "Mikoto Saito",
    card: "../assets/card-img/krysrain.png",
    nation: "Lyrical Monasterio",
    main: "Fated One of Ever-changing, Krysrain",
    level: ["Hard", "Very Hard"],
  },
  {
    id: 24,
    fighter: "Doshi Nakano",
    card: "../assets/card-img/eugene.png",
    nation: "Dragon Empire",
    main: "Heavy Artillery of Dust Storm, Eugene",
    level: ["Easy", "Normal", "Hard", "Very Hard"],
  },
  {
    id: 27,
    fighter: "Noi Taito",
    card: "../assets/card-img/tamayura.png",
    nation: "Dragon Empire",
    main: "Will-o-wisp Daybreak, Tamayura",
    level: ["Easy", "Normal", "Hard", "Very Hard"],
  },
  {
    id: 28,
    fighter: "Otawa Dosaki",
    card: "../assets/card-img/wirbel.png",
    nation: "Dragon Empire",
    main: "Hellfire Dragon, Wirbel Dragon",
    level: ["Hard", "Very Hard"],
  },
  {
    id: 29,
    fighter: "Roh Nijo",
    card: "../assets/card-img/shiranui.png",
    nation: "Dragon Empire",
    main: 'Demon Stealth Dragon, Shiranui "Oboro"',
    level: ["Very Hard"],
  },
  {
    id: 30,
    fighter: "Yu-yu Kondo",
    card: "../assets/card-img/nirvana.png",
    nation: "Dragon Empire",
    main: "Chakrabarthi Phoenix Dragon, Nirvana Jheva",
    level: ["Very Hard"],
  },
  {
    id: 31,
    fighter: "Mirei Minae",
    card: "../assets/card-img/bavsargra.png",
    nation: "Dragon Empire",
    main: "Sealed Blaze Maiden, Bavsargra",
    level: ["Hard", "Very Hard"],
  },
  {
    id: 32,
    fighter: "Nao Inabe",
    card: "../assets/card-img/varga.png",
    nation: "Dragon Empire",
    main: "Fated One of Unparalleled, Varga Dragres",
    level: ["Hard", "Very Hard"],
  },
  {
    id: 33,
    fighter: "Zero Tendo",
    card: "../assets/card-img/vyrgilla.png",
    nation: "Dragon Empire",
    main: "Rewrite the Star, Vyrgilla",
    level: ["Very Hard"],
  },
  {
    id: 34,
    fighter: "Taiji Arakawa",
    card: "../assets/card-img/eva.png",
    nation: "Brandt Gate",
    main: "Fountain of Knowledge, Eva",
    level: ["Easy", "Normal", "Hard", "Very Hard"],
  },
  {
    id: 35,
    fighter: "Zakusa Ishigame",
    card: "../assets/card-img/orfist.png",
    nation: "Brandt Gate",
    main: "Cardinal Dominus, Orfist Regis",
    level: ["Hard", "Very Hard"],
  },
  {
    id: 36,
    fighter: "Tomari Seto",
    card: "../assets/card-img/prison.png",
    nation: "Brandt Gate",
    main: "Aurora Fierce Princess, Seraph Purelight",
    level: ["Hard", "Very Hard"],
  },
  {
    id: 37,
    fighter: "Taizo Kiyokura",
    card: "../assets/card-img/welstra.png",
    nation: "Brandt Gate",
    main: 'Fated One of Guiding Star, Welstra "Blitz Arms"',
    level: ["Hard", "Very Hard"],
  },
  {
    id: 38,
    fighter: "Jinki Mukae",
    card: "../assets/card-img/alden.png",
    nation: "Keter Sanctuary",
    main: "Destined One of Protection, Alden",
    level: ["Very Hard"],
  },
  {
    id: 39,
    fighter: "Senka Kanae",
    card: "../assets/card-img/impauldio.png",
    nation: "Brandt Gate",
    main: "Destined One of Exceedance, Impauldio",
    level: ["Very Hard"],
  },
  {
    id: 40,
    fighter: "Kyohma Kurosaki",
    card: "../assets/card-img/aelquilibra.png",
    nation: "Dragon Empire",
    main: "Destined One of Scales, Aelquilibra",
    level: ["Very Hard"],
  },
  {
    id: 41,
    fighter: "Yuna Saionji",
    card: "../assets/card-img/lisciafael.png",
    nation: "Lyrical Monasterio",
    main: "Destined One of Supremacy, Lisciafael",
    level: ["Very Hard"],
  },
  {
    id: 42,
    fighter: "Kuon Aikawa",
    card: "../assets/card-img/levidras.png",
    nation: "Stoicheia",
    main: "Destined One of Infinity, Levidras",
    level: ["Very Hard"],
  },
  {
    id: 43,
    fighter: "Sybilt Nao",
    card: "../assets/card-img/rakshasa.png",
    nation: "Dragon Empire",
    main: `Unparalleled Drekasleif, Varga Dragres "Rakshasa"`,
    level: ["Very Hard"],
  },
  {
    id: 44,
    fighter: "Hikari (Young)",
    card: "../assets/card-img/odium.png",
    nation: "Dark States",
    main: "Destined One of Time, Liael=Odium",
    level: ["Very Hard"],
  },
];

export default Fighters;
